core/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="To Do API",
        default_version="v1",
        description="Test API for Todo's Task model",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="malekpour.projects@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("", lambda request: redirect("todo/")),
    path("todo/", include("todo.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/todo/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from .views import (
    TaskListView,
    TaskCreateView,
    TaskStatusView,
    TaskUpdateView,
    TaskDeleteView,
    weather_status_view,
)

app_name = "todo"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("todo:tasks")), name="home"),
    path("tasks", TaskListView.as_view(), name="tasks"),
    path("task/create/", TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/edit/", TaskUpdateView.as_view(), name="update-task"),
    path("task/<int:pk>/complete/", TaskStatusView.as_view(), name="complete-task"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="delete-task"),
    path("weather", weather_status_view, name="weather"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>To Do App</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    
    {% block css_links %} {% endblock css_links %}
  </head>
  <body class="vh-100" style="background-color: #eee;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/todo/' %} active {% endif %}" 
                href="{% url 'todo:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/todo/tasks' %} active {% endif %}" 
              href="{% url 'todo:tasks' %}">Tasks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/todo/weather' %} active {% endif %}" 
              href="{% url 'todo:weather' %}">Weather</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/accounts/login/' %} active {% endif %}" 
                href="{% url 'accounts:login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <main>
      {% block main_content %} {% endblock main_content %}
    </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>