core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="To Do API",
        default_version="v1",
        description="Test API for Todo's Task model",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="malekpour.projects@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("", lambda request: redirect("todo/")),
    path("todo/", include("todo.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/todo/api/v1/urls.py
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")
urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from .views import (
    TaskListView,
    TaskCreateView,
    TaskStatusView,
    TaskUpdateView,
    TaskDeleteView,
    weather_status_view,
)

app_name = "todo"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("todo:tasks")), name="home"),
    path("tasks", TaskListView.as_view(), name="tasks"),
    path("task/create/", TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/edit/", TaskUpdateView.as_view(), name="update-task"),
    path("task/<int:pk>/complete/", TaskStatusView.as_view(), name="complete-task"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="delete-task"),
    path("weather", weather_status_view, name="weather"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Task(models.Model):
    owner = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    is_completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} - {self.title}"

    def get_relative_api_url(self):
        return reverse("todo:api-v1:task-detail", kwargs={"pk": self.pk})

core/todo/api/v1/views.py
from rest_framework import viewsets
from .serializers import TaskSerializer
from .permissions import IsAuthenticatedOwner
from .paginations import CustomDefaultPagination
from todo.models import Task
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter


class TaskModelViewSet(viewsets.ModelViewSet):
    """
    Retrieving task and creating a task \n
    Retrieving, Updating and Deleting a single task
    """

    permission_classes = [IsAuthenticatedOwner]
    serializer_class = TaskSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    pagination_class = CustomDefaultPagination
    filterset_fields = ["is_completed", "created_date"]
    search_fields = ["title"]
    ordering_fields = ["created_date", "is_completed"]

    def get_queryset(self):
        return Task.objects.filter(owner__user__id=self.request.user.id)

core/todo/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.decorators.cache import cache_page
from django.core.cache import cache

import requests

from .models import Task
from accounts.models import Profile


# Create your views here.
class TaskListView(LoginRequiredMixin, ListView):
    """
    Showing a list of tasks based on the current user's list of tasks
    """

    template_name = "todo/task-list.html"
    context_object_name = "tasks"

    def get_queryset(self):
        tasks = Task.objects.filter(owner__user__id=self.request.user.id)
        return tasks


class TaskCreateView(LoginRequiredMixin, CreateView):
    """
    Creating a new task and dedicating this task to the current user
    """

    template_name = "todo/task-list.html"
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:tasks")

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user__id=self.request.user.id)
        return super().form_valid(form)


class TaskStatusView(LoginRequiredMixin, View):
    """
    Updating task is_completed field status
    """

    def get(self, request, *args, **kwargs):
        task = Task.objects.get(id=kwargs.get("pk"))
        if not task.is_completed:
            task.is_completed = True
        else:
            task.is_completed = False
        task.save()
        return redirect(reverse_lazy("todo:tasks"))


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updating a specific task
    """

    template_name = "todo/update-task.html"
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:tasks")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deleting specified task
    """

    model = Task
    template_name = "todo/task-list.html"
    success_url = reverse_lazy("todo:tasks")

    def get(self, request, *args, **kwargs):
        # returning a post request to by-pass the delete confirmation
        return self.post(request, *args, **kwargs)


@cache_page(60 * 20)
def weather_status_view(request):
    """View for Tehran Weather Report"""
    # Tehran Latitude
    latitude = "35.6944"
    # Tehran Longitude
    longitude = "51.4215"
    # Open Weather account API key
    API_KEY = "267a2f751f81f0cfed52040be37fc89c"
    response = requests.get(
        f"https://api.openweathermap.org/data/2.5/weather?lat={latitude}&lon={longitude}&units=metric&appid={API_KEY}"
    )
    if response.status_code == 200:
        weather_report = response.json()
    else:
        weather_report = None
    context = {"weather_report": weather_report}
    return render(request, "todo/weather.html", context)


def weather_status_view_2(request):
    """View for Tehran Weather Report - Manual Caching"""

    if cached_response := cache.get("weather_report_cache"):
        context = {"weather_report": cached_response}
        return render(request, "todo/weather.html", context)

    # Tehran Latitude
    latitude = "35.6944"
    # Tehran Longitude
    longitude = "51.4215"
    # Open Weather account API key
    API_KEY = "267a2f751f81f0cfed52040be37fc89c"
    response = requests.get(
        f"https://api.openweathermap.org/data/2.5/weather?lat={latitude}&lon={longitude}&units=metric&appid={API_KEY}"
    )
    if response.status_code == 200:
        weather_report = response.json()
        cache.set("weather_report_cache", weather_report, 60 * 20)
    else:
        weather_report = None
    context = {"weather_report": weather_report}
    return render(request, "todo/weather.html", context)

core/templates/todo/task-list.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}
  <section class="h-100 w-100" style="background-color: #eee;">
    <div class="container py-2 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-12 col-xl-12">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">To Do App</h4>
              {% if form.errors %}
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <p class="text-danger ps-5">
                  {{ field.name|title }} - {{ error|escape }}
                </p>
                {% endfor %}
                {% endif %}
                {% endfor %}
              {% endif %}
              <form class="row g-3 text-center mb-4 pb-2" method="post" action="{% url 'todo:create-task' %}">
                {% csrf_token %}
                <div class="col-9 ps-5">
                  <div class="form-outline">
                    <input type="text" id="task-title" name="title" class="form-control" placeholder="Enter a task here"/>
                  </div>
                </div>

                <div class="d-grid col-3 pe-5">
                  <button type="submit" class="btn btn-outline-primary">Add Task</button>
                </div>

              </form>

              <table class="table mb-4">
                <thead>
                  <tr>
                    <th scope="col">Todo item</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  
                  {% for task in tasks %}
                    <tr>
                      <td class="col-8 
                      {% if task.is_completed %}
                        text-decoration-line-through
                      {% endif %}
                        "> {{task.title|title}} </td>
                      <td class="col-4">
                        {% if task.is_completed %}
                          <a type="button" class="btn btn-warning" href="{% url 'todo:complete-task' pk=task.id %}">
                            Undone
                          </a>
                        {% else %}
                          <a type="button" class="btn btn-success" href="{% url 'todo:complete-task' pk=task.id %}">
                            Done
                          </a>
                          {% endif %}
                          
                          <a type="button" class="btn btn-primary" href="{% url 'todo:update-task' pk=task.id %}">
                            Edit
                          </a>

                          <a type="button" class="btn btn-danger" href="{% url 'todo:delete-task' pk=task.id %}">
                            Delete
                          </a>

                      </td>
                    </tr>
                  {% endfor %}
                    
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

core/templates/todo/update-task.html
{% extends 'base.html' %}

{% block main_content %}
<div class="col col-lg-12 col-xl-12">
    <div class="card rounded-3">
      <div class="card-body p-4">
        <h4 class="text-center my-3 pb-3">To Do App</h4>
        {% if form.errors %}
          {% for field in form %}
          {% if field.errors %}
          {% for error in field.errors %}
          <p class="text-danger ps-5">
            {{ field.name|title }} - {{ error|escape }}
          </p>
          {% endfor %}
          {% endif %}
          {% endfor %}
        {% endif %}
        <form class="row g-3 text-center mb-4 pb-2" method="post" action="{% url 'todo:update-task' pk=task.id %}">
          {% csrf_token %}
          <div class="col-9 ps-5">
            <div class="form-outline">
              <input type="text" id="task-title" name="title" class="form-control" placeholder="Task Title" value="{{ task.title }}"/>
            </div>
          </div>

          <div class="d-grid col-3 pe-5">
            <button type="submit" value="Update" class="btn btn-outline-success">Update</button>
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/todo/weather.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}
  <section class="h-100 w-100" style="background-color: #eee;">
    <div class="container py-2 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-12 col-xl-12">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">«Weather»</h4>
              <div class="text-center">
                {% if weather_report %}
                  <p class="fs-4">City: {{ weather_report.name }}</p>
                  <p class="fs-4">Weather Condition: {{ weather_report.weather.0.description }}</p>
                  <p class="fs-4">Temperature: {{ weather_report.main.temp }}</p>
                  <p class="fs-4">Wind speed: {{ weather_report.wind.speed }}</p>
                {% else %}
                  <p class="fs-4">Sorry, weather report was not availabe. Please try again!</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}